# Generated by CodiumAI
import unittest
from PySide6.QtWidgets import QApplication
from ui.adc_controlpanel import ADCConfigWidget

app = QApplication.instance()
if not app:
    app = QApplication([])


class TestADCConfigWidget(unittest.TestCase):

    def setUp(self) -> None:
        self.widget = ADCConfigWidget()

    def test_initialized_with_default_values(self) -> None:
        """ADCConfigWidget is initialized with default values"""

        config_values = self.widget.get_config_values()
        self.assertEqual(config_values["address"], "0x48")
        self.assertEqual(config_values["gain"], "±6.144V (Default)")
        self.assertEqual(config_values["data_rate"], "128 SPS (Default)")
        self.assertTrue(config_values["polling_mode"])

    def test_select_address_from_combo_box(self) -> None:
        """User can select an address from the address combo box."""
        self.widget.address_combo.setCurrentIndex(1)
        config_values = self.widget.get_config_values()
        self.assertEqual(config_values["address"], "0x49")

    def test_select_gain_from_combo_box(self) -> None:
        """User can select a gain from the gain combo box."""
        self.widget.gain_combo.setCurrentIndex(2)
        config_values = self.widget.get_config_values()
        self.assertEqual(config_values["gain"], "±2.048V")

    def test_address_combo_box_empty(self) -> None:
        """Address combo box is empty."""
        self.widget.address_combo.clear()
        self.assertEqual(self.widget.address_combo.count(), 0)

    def test_gain_combo_box_empty(self) -> None:
        """Gain combo box is empty."""
        self.widget.gain_combo.clear()
        self.assertEqual(self.widget.gain_combo.count(), 0)

    def test_data_rate_combo_box_empty(self) -> None:
        """Data rate combo box is empty."""
        self.widget.data_rate_combo.clear()
        self.assertEqual(self.widget.data_rate_combo.count(), 0)
